services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Trueprogramming\ForcePasswordReset\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Trueprogramming\ForcePasswordReset\Listener\PasswordChangedListener:
    tags:
      - name: event.listener
        identifier: 'trueprogramming-forcepasswordreset-paswordchanged'
