services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Trueprogramming\ForcePasswordReset\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Trueprogramming\ForcePasswordReset\Listener\PasswordChangedListener:
    tags:
      - name: event.listener
        identifier: 'trueprogramming-forcepasswordreset-paswordchanged'

  Trueprogramming\ForcePasswordReset\Command\SetResetForAllUsersCommand:
    tags:
      - name: 'console.command'
        command: 'forcepasswordreset:setResetForAllUsers'
        description: 'Sets password reset for all frontend users in database'
